GET http://localhost?limit=10000 HTTP/1.1

###
GET http://localhost/ping?limit=10000 HTTP/1.1

###
GET http://kp.sing3demons/health HTTP/1.1
###
GET http://kp.sing3demons?limit=1000 HTTP/1.1

###
GET http://localhost/health HTTP/1.1