apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-client
  namespace: go-kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: go-client
          image: sing3demons/go-client:1.2
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 4
            failureThreshold: 4
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 5
          env:
            - name: SERVER_URL
              value: "http://server:8080/api/v1/get_something"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: go-kubernetes
spec:
  selector:
    app: client
  ports:
    - port: 8081
      targetPort: 8081
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: my-ingress
#   annotations:
#       kubernetes.io/ingress.class: nginx
#   namespace: go-kubernetes
#   labels:
#     name: my-ingress
# spec:
#   rules:
#   - host: kp.sing3demons
#     http:
#       paths:
#       - pathType: Prefix
#         path: /
#         backend:
#           service:
#             name: client
#             port:
#               number: 8081
