apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  namespace: go-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: go-server
          image: sing3demons/go-server:1.2
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 4
            failureThreshold: 4
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 5
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: go-kubernetes
spec:
  selector:
    app: server
  ports:
  - port: 8080
    targetPort: 8080
